### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/the-lodge#2]
We are gong to need some graphic design work. We are going to need a design for the website home page, the website inside pages, and a web style guide. We are also going to need some design work for the iOS and Android apps too.

Maybe we can get volunteers, but most likely we will have to rely on High Fives internal designers, or a marketing/design agency.  Thoughts??

**Comment by eveporcello** [comment]
Have approached [Kimberly Lennex](http://elamora.me/) about this and she really wants to work on the project. Will follow up with her after the wireframes are locked.
